opam-version: "2.0"
name: "rocq-of-rust"
version: "dev"
synopsis: "Rocq of Rust"
description: """
Formal verification for Rust by translation to the proof system Rocq
"""
maintainer: "Guillaume Claret <dev@clarus.me>"
authors: [
  "Formal Land <contact@formal.land>"
]
license: "MIT"
homepage: "https://formal.land/docs/rocq-of-rust/introduction"
bug-reports: "https://github.com/formal-land/rocq-of-rust/issues"
dev-repo: "git+https://github.com/theorem-labs/rocq-of-rust.git"
depends: [
  "coq-coqutil"
  "coq-hammer-tactics"
  "rocq-core" {>= "9.0" & < "9.4"}
  "rocq-smpl"
  "rocq-stdlib"
]
build: [
  ["bash" "-c" "cd RocqOfRust && ulimit -s unlimited && make -j%{jobs}%"]
]
install: [
  ["make" "-C" "RocqOfRust" "install"]
]
